name: formix_docs
description: A documentation site built with Jaspr
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.3
  jaspr_content: ^0.5.0
  jaspr_router: ^0.8.1
  syntax_highlight_lite: any

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.12
  jaspr_builder: ^0.22.3
  lints: ^5.0.0

jaspr:
  mode: static
