name: formix_docs
description: A documentation site built with Jaspr
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  jaspr: ^0.22.3
  jaspr_content: ^0.5.0
  jaspr_lucide: ^0.16.1
  jaspr_router: ^0.8.1
  jaspr_riverpod: ^0.4.4
  jaspr_flutter_embed:
    path: local_packages/jaspr_flutter_embed
  syntax_highlight_lite: any
  universal_web: ^1.1.1+1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.12
  jaspr_builder: ^0.22.3
  jaspr_tailwind: ^0.3.6
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

jaspr:
  mode: static
  flutter: embedded

flutter:
  uses-material-design: true

